name: CI/CD with Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 134
          check-latest: true

      - name: Run tests
        run: |
          mvn clean test -B \
            -Dwebdriver.chrome.whitelistedIps="" \
            -DchromeOptions.args="--headless=new,--no-sandbox,--disable-dev-shm-usage"

      - name: Generate Allure report
        run: allure generate target/allure-results -o target/allure-report --clean

      - name: Deploy Allure Report
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
          keep_files: true
