name: CI/CD with Allure Report

on:
  push:
    branches:
      - main  # Или другая ветка, где должны запускаться тесты
  pull_request:

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    env:
      CHROME_VERSION: 114 # Задайте здесь нужную версию Chrome, соответствующую вашему ChromeDriver

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Download ChromeDriver
        uses: elozano/download-chromedriver@v1
        with:
          chromedriver_version: 114 # Версия ChromeDriver должна соответствовать CHROME_VERSION
          chromedriver_platform: linux64

      - name: Add ChromeDriver to PATH
        run: echo $GITHUB_WORKSPACE/chromedriver/chromedriver >> $GITHUB_PATH

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Ⓑ/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn clean test -B -Dwebdriver.chrome.driver=$GITHUB_WORKSPACE/chromedriver/chromedriver

      - name: Generate Allure report
        run: allure generate target/allure-results -o target/allure-report --clean

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report

      - name: Deploy Allure Report (if on main branch)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
          keep_files: true
